export const FETCH_AUTH_REQUEST = "FETCH_AUTH_REQUEST";
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS";
export const FETCH_AUTH_ERROR = "FETCH_AUTH_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const NO_ERROR = "LOGOUT_USER";

export const FETCH_REFRESH_TOKEN_REQUEST =
  "FETCH_REFRESH_TOKEN_REQUEST";
export const FETCH_REFRESH_TOKEN_SUCCESS =
  "FETCH_REFRESH_TOKEN_SUCCESS";
export const FETCH_REFRESH_TOKEN_ERROR =
  "FETCH_REFRESH_TOKEN_ERROR";


